# appveyor.yml reference : http://www.appveyor.com/docs/appveyor-yml

version: "1.1.0.{build}"

# Source Config
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
clone_folder: c:\gopath\src\github.com\pecigonzalo\docker-machine-vmwareworkstation
clone_depth: 5

# Build host

os: Windows Server 2012 R2

environment:
  MSYSTEM: MINGW64
  Msys: winsymlink:nativestrict
  GOPATH: c:\gopath
  Path: c:\go\bin;c:\gopath\bin;C:\msys64\usr\local\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  matrix:
  - GOARCH: 386
    GOVERSION: 1.6
  - GOARCH: amd64
    GOVERSION: 1.6

init:
  - ps: git config --global core.autocrlf input
  - pacman -Sy
  - pacman -S --noconfirm make wget curl bzr git mercurial subversion

# Build
install:
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GOARCH%.msi
  - msiexec /i go%GOVERSION%.windows-%GOARCH%.msi /q
  - ps: echo $env:Path
  - make deps

cache:
  - '%USERPROFILE%\.glide\cache'

build_script:
  - git rev-parse HEAD
  - make test
  - make build

test: off

# Deploy
artifacts:
  - path: //bin/docker-machine-driver-vmwareworkstation.exe

deploy:
  provider: GitHub
  description: ' '
  auth_token:
    secure: QqxdbpN5rJhuQw42Iq4W6tdP1Lu4aw6y88QnHYC3tSQ9rzNuEI/q+qH4HGJ5WDpj
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only